import { SpeedInsights } from '@vercel/speed-insights/next'
import ReactLenis from 'lenis/react'
import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'

import { Footer } from '@/components'

import 'material-symbols'
import './globals.css'

const outfit = Outfit({
  display: 'swap',
  style: 'normal',
  subsets: ['latin'],
  variable: '--font-outfit'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.variable} font-outfit antialiased`}>
        <ReactLenis root>
          {children}
          <Footer />
        </ReactLenis>
        <SpeedInsights />
      </body>
    </html>
  )
}
